Control Loops

In [2]:
# Loops
n = 0
while n < 10
    n += 1
    println(n)
end


1
2
3
4
5
6
7
8
9
10


In [3]:
names = ["John", "Paul", "George", "Ringo"]
i = 1
while i <= length(names)
    friend = names[i]
    println("Hello, $friend")
    i += 1
end

Hello, John
Hello, Paul
Hello, George
Hello, Ringo


In [4]:
#for Loops
for n in 1:10
    println(n)
end 


1
2
3
4
5
6
7
8
9
10


In [12]:
for name in ["John", "Mary", "Bob", "Jane", "Mark"]
    println("Hello, $(name)!")
end
println("\n")
for name = ["John", "Mary", "Bob", "Jane", "Mark"]
    println("Hello, $(name)!")
end
println("\n")
for name ∈ ["John", "Mary", "Bob", "Jane", "Mark"]
    println("Hello, $(name)!")
end


Hello, John!
Hello, Mary!
Hello, Bob!
Hello, Jane!
Hello, Mark!


Hello, John!
Hello, Mary!
Hello, Bob!
Hello, Jane!
Hello, Mark!


Hello, John!
Hello, Mary!
Hello, Bob!
Hello, Jane!
Hello, Mark!


In [14]:
m, n = 5, 5
A = zeros(m, n)
println(A)
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
println(A)

[0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0]
[2.0 3.0 4.0 5.0 6.0; 3.0 4.0 5.0 6.0 7.0; 4.0 5.0 6.0 7.0 8.0; 5.0 6.0 7.0 8.0 9.0; 6.0 7.0 8.0 9.0 10.0]


In [17]:
B = zeros(m, n)
println(B)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

[0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0]


5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [16]:
# The best way
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Conditional Statements

In [21]:
x = 90
y = 90

if x > y
    println("$x is greater than $y")
elseif x < y
    println("$x is less than $y")
else
    println("$x is equal to $y")
end

90 is equal to 90


In [22]:
# Ternary Operator
x = 3
y = 90

(x > y) ? "$x is greater than $y" : "$y is greater than $x"

"90 is greater than 3"

In [23]:
# Short Circuit evaluation
(x > y) && println("$x is greater than $y") # anything after && is not evaluated if the condition is false
(x < y) && println("$x is less than $y")

3 is less than 90


Functions

In [24]:
function sayhi(name)
    println("Hi, $name")
end

sayhi (generic function with 1 method)

In [25]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [26]:
sayhi("Uddhava")


Hi, Uddhava


In [27]:
f(42)

1764

In [29]:
# Single line declerations
sayhi2(name) = println("Hi $name")
f2(x) = x^2

f2 (generic function with 1 method)

In [30]:
sayhi2("Uddhava")

Hi Uddhava


In [31]:
f2(10)

100

In [32]:
sayhi3 = name -> println("Hi, $(name)!")
f3 = x -> x^2


#13 (generic function with 1 method)

In [33]:
sayhi3("Uddhava")
f3(42)

Hi, Uddhava!


1764

In [34]:
sayhi(12949134) # This works

A = rand(3, 3)
A

Hi, 12949134


3×3 Matrix{Float64}:
 0.561268  0.187162  0.0443825
 0.292185  0.883042  0.217849
 0.471518  0.727002  0.99721

In [35]:
f(A)

3×3 Matrix{Float64}:
 0.390635  0.302586  0.109942
 0.524726  0.992826  0.42258
 0.94727   1.4552    1.17373

In [36]:
v = rand(3)
f(v) # error because v^2 is not defined

MethodError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)

Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::Integer)
   @ Base mathconstants.jl:119
  ^(!Matched::BigFloat, ::Integer)
   @ Base mpfr.jl:670
  ^(!Matched::Float64, ::Integer)
   @ Base math.jl:1246
  ...


Functions that are followed by an ! alter their inputs.

In [37]:
v = [3, 5, 2]

3-element Vector{Int64}:
 3
 5
 2

In [38]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [39]:
v

3-element Vector{Int64}:
 3
 5
 2

In [40]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [41]:
v

3-element Vector{Int64}:
 2
 3
 5

In [42]:
# Broadcasting (element-wise vs matrix operation)
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [43]:
f(A) # A*A

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [44]:
f.(A) # elementwise squaring of A

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [45]:
v = [3, 5, 2]
f.(v) # This works

3-element Vector{Int64}:
  9
 25
  4